leg = [
("Bradley Byrne","RepByrne"),
("Martha Roby","RepMarthaRoby"),
("Mike Rogers","RepMikeRogersAL"),
("Robert B. Aderholt","Robert_Aderholt"),
("Mo Brooks","RepMoBrooks"),
("Gary J. Palmer","USRepGaryPalmer"),
("Terri A. Sewell","RepTerriSewell"),
("Eric A. \"Rick\" Crawford","RepRickCrawford"),
("J. French Hill","RepFrenchHill"),
("Steve Womack","rep_stevewomack"),
("Bruce Westerman","RepWesterman"),
("Ann Kirkpatrick","RepKirkpatrick"),
("Raul M. Grijalva","RepRaulGrijalva"),
("Paul A. Gosar","RepGosar"),
("David Schweikert","RepDavid"),
("Ruben Gallego","RepRubenGallego"),
("Doug LaMalfa","RepLaMalfa"),
("Mark DeSaulnier","RepDeSaulnier"),
("Nancy Pelosi","SpeakerPelosi"),
("Barbara Lee","RepBarbaraLee"),
("Jackie Speier","RepSpeier"),
("Eric Swalwell","RepSwalwell"),
("Jim Costa","RepJimCosta"),
("Jared Huffman","RepHuffman"),
("Devin Nunes","RepDevinNunes"),
("Kevin McCarthy","GOPLeader"),
("Julia Brownley","RepBrownley"),
("Judy Chu","RepJudyChu"),
("Tony Cardenas","RepCardenas"),
("John Garamendi","RepGaramendi"),
("Pete Aguilar","RepPeteAguilar"),
("Grace F. Napolitano","gracenapolitano"),
("Ted Lieu","RepTedLieu"),
("Norma J. Torres","NormaJTorres"),
("Raul Ruiz","CongressmanRuiz"),
("Karen Bass","RepKarenBass"),
("Linda T. Sanchez","RepLindaSanchez"),
("Tom McClintock","RepMcClintock"),
("Lucille Roybal-Allard","RepRoybalAllard"),
("Mark Takano","RepMarkTakano"),
("Maxine Waters","RepMaxineWaters"),
("Alan S. Lowenthal","RepLowenthal"),
("Mike Thompson","RepThompson"),
("Juan Vargas","RepJuanVargas"),
("Scott H. Peters","RepScottPeters"),
("Susan A. Davis","RepSusanDavis"),
("Doris O. Matsui","DorisMatsui"),
("Ami Bera","RepBera"),
("Paul Cook","RepPaulCook"),
("Jerry McNerney","RepMcNerney"),
("Diana DeGette","RepDianaDeGette"),
("Scott R. Tipton","RepTipton"),
("Ken Buck","RepKenBuck"),
("Doug Lamborn","RepDLamborn"),
("Ed Perlmutter","RepPerlmutter"),
("Joe Courtney","RepJoeCourtney"),
("James A. Himes","jahimes"),
("Daniel Webster","RepWebster"),
("Gus M. Bilirakis","RepGusBilirakis"),
("Kathy Castor","USRepKCastor"),
("Vern Buchanan","VernBuchanan"),
("Lois Frankel","RepLoisFrankel"),
("Debbie Wasserman Schultz","RepDWStweets"),
("Frederica S. Wilson","RepWilson"),
("Mario Diaz-Balart","MarioDB"),
("Ted S. Yoho","RepTedYoho"),
("Bill Posey","congbillposey"),
("Earl L. \"Buddy\" Carter","RepBuddyCarter"),
("Jody B. Hice","CongressmanHice"),
("Barry Loudermilk","RepLoudermilk"),
("Rick W. Allen","RepRickAllen"),
("David Scott","repdavidscott"),
("Tom Graves","RepTomGraves"),
("Henry C. \"Hank\" Johnson Jr.","RepHankJohnson"),
("Rob Woodall","RepRobWoodall"),
("Austin Scott","AustinScottGA08"),
("Doug Collins","RepDougCollins"),
("Tulsi Gabbard","TulsiPress"),
("David Loebsack","daveloebsack"),
("Steve King","SteveKingIA"),
("Michael K. Simpson","CongMikeSimpson"),
("Bobby L. Rush","RepBobbyRush"),
("Bill Foster","RepBillFoster"),
("Mike Bost","RepBost"),
("Rodney Davis","RodneyDavis"),
("John Shimkus","RepShimkus"),
("Adam Kinzinger","RepKinzinger"),
("Cheri Bustos","RepCheri"),
("Robin L. Kelly","RepRobinKelly"),
("Mike Quigley","RepMikeQuigley"),
("Danny K. Davis","RepDannyDavis"),
("Janice \"Jan\" D. Schakowsky","janschakowsky"),
("Jackie Walorski","RepWalorski"),
("Susan W. Brooks","SusanWBrooks"),
("Andre Carson","RepAndreCarson"),
("Larry Bucshon","RepLarryBucshon"),
("Brett Guthrie","RepGuthrie"),
("John A. Yarmuth","RepJohnYarmuth"),
("Thomas Massie","RepThomasMassie"),
("Andy Barr","RepAndyBarr"),
("Steve Scalise","SteveScalise"),
("Cedric L. Richmond","RepRichmond"),
("Ralph Lee Abraham","RepAbraham"),
("Garret Graves","RepGarretGraves"),
("Gregorio Kilili Camacho Sablan", "Kilili_Sablan"),
("Joseph Kennedy III","RepJoeKennedy"),
("Katherine M. Clark","RepKClark"),
("Seth Moulton","teammoulton"),
("William R. Keating","USRepKeating"),
("Stacey Plaskett", "StaceyPlaskett"),
("Aumua Amata Coleman Radewagen", "RepAmata"),
("Tom O’Halleran","RepOHalleran"),
("Drew Ferguson IV","RepDrewFerguson"),
("Andy Harris","RepAndyHarrisMD"),
("Jenniffer Gonzalez-Colon", "RepJenniffer"),
("Michael San Nicolas", "GuamCongressman"),
("Jesus Garcia", "ChuyForCongress"),
("William Timmons IV","RepTimmons"),
("Abigail Davis Spanberger", "RepSpanberger"),
("Dan Bishop", "jdanbishop"),
("Gregory Murphy","RepGregMurphy"),
("C. A. Dutch Ruppersberger","Call_Me_Dutch"),
("John P. Sarbanes","RepSarbanes"),
("Debbie Dingell","RepDebDingell"),
("Brenda L. Lawrence","RepLawrence"),
("Bill Huizenga","RepHuizenga"),
("Justin Amash","justinamash"),
("John R. Moolenaar","RepMoolenaar"),
("Daniel T. Kildee","RepDanKildee"),
("Fred Upton","RepFredUpton"),
("Tim Walberg","RepWalberg"),
("Betty McCollum","BettyMcCollum04"),
("Tom Emmer","RepTomEmmer"),
("Wm. Lacy Clay Jr","LacyClayMO1"),
("Ann Wagner","RepAnnWagner"),
("Blaine Luetkemeyer","RepBlaine"),
("Vicky Hartzler","RepHartzler"),
("Emanuel Cleaver","repcleaver"),
("Billy Long","USRepLong"),
("Jason Smith","RepJasonSmith"),
("Trent Kelly","RepTrentKelly"),
("Steven M. Palazzo","CongPalazzo"),
("G. K. Butterfield","GKButterfield"),
("Patrick T. McHenry","PatrickMcHenry"),
("Mark Meadows","RepMarkMeadows"),
("Alma S. Adams","RepAdams"),
("George Holding","RepHolding"),
("David E. Price","RepDavidEPrice"),
("Virginia Foxx","virginiafoxx"),
("Mark Walker","RepMarkWalker"),
("Richard Hudson","RepRichHudson"),
("Adrian Smith","RepAdrianSmith"),
("Ann M. Kuster","RepAnnieKuster"),
("Donald Norcross","DonaldNorcross"),
("Donald M. Payne, Jr.","RepDonaldPayne"),
("Bonnie Watson Coleman","RepBonnie"),
("Albio Sires","RepSires"),
("Bill Pascrell, Jr.","BillPascrell"),
("Ben Ray Lujan","repbenraylujan"),
("Dina Titus","repdinatitus"),
("Mark E. Amodei","MarkAmodeiNV2"),
("Lee M. Zeldin","RepLeeZeldin"),
("Jerrold Nadler","RepJerryNadler"),
("Carolyn B. Maloney","RepMaloney"),
("Jose E. Serrano","RepJoseSerrano"),
("Sean Patrick Maloney","RepSeanMaloney"),
("Paul Tonko","RepPaulTonko"),
("Elise M. Stefanik","RepStefanik"),
("Tom Reed","RepTomReed"),
("John Katko","RepJohnKatko"),
("Chris Collins","RepChrisCollins"),
("Kathleen M. Rice","RepKathleenRice"),
("Grace Meng","RepGraceMeng"),
("Nydia M. Velazquez","NydiaVelazquez"),
("Hakeem S. Jeffries","RepJeffries"),
("Yvette D. Clarke","RepYvetteClarke"),
("Michael R. Turner","RepMikeTurner"),
("Marcia L. Fudge","RepMarciaFudge"),
("Tim Ryan","RepTimRyan"),
("David P. Joyce","RepDaveJoyce"),
("Steve Stivers","RepSteveStivers"),
("Brad R. Wenstrup","RepBradWenstrup"),
("Joyce Beatty","RepBeatty"),
("Jim Jordan","Jim_Jordan"),
("Robert E. Latta","boblatta"),
("Bill Johnson","RepBillJohnson"),
("Bob Gibbs","RepBobGibbs"),
("Markwayne Mullin","RepMullin"),
("Frank D. Lucas","RepFrankLucas"),
("Tom Cole","TomColeOK04"),
("Suzanne Bonamici","RepBonamici"),
("Greg Walden","repgregwalden"),
("Kurt Schrader","RepSchrader"),
("Brendan Boyle","CongBoyle"),
("Matt Cartwright","RepCartwright"),
("Mike Kelly","MikeKellyPA"),
("Scott Perry","RepScottPerry"),
("Glenn Thompson","CongressmanGT"),
("David N. Cicilline","RepCicilline"),
("James R. Langevin","JimLangevin"),
("Joe Wilson","RepJoeWilson"),
("Jeff Duncan","RepJeffDuncan"),
("Tom Rice","RepTomRice"),
("David P. Roe","DrPhilRoe"),
("Charles J. \"Chuck\" Fleischmann","RepChuck"),
("Scott DesJarlais","DesJarlaisTN04"),
("Steve Cohen","RepCohen"),
("Louie Gohmert","replouiegohmert"),
("Michael T. McCaul","RepMcCaul"),
("K. Michael Conaway","ConawayTX11"),
("Kay Granger","RepKayGranger"),
("Mac Thornberry","MacTXPress"),
("Randy K. Weber, Sr.","TXRandy14"),
("Bill Flores","RepBillFlores"),
("Joaquin Castro","JoaquinCastrotx"),
("Pete Olson","RepPeteOlson"),
("Will Hurd","HurdOnTheHill"),
("Kenny Marchant","RepKenMarchant"),
("Roger Williams","RepRWilliams"),
("Michael C. Burgess","michaelcburgess"),
("Henry Cuellar","RepCuellar"),
("John R. Carter","JudgeCarter"),
("Marc A. Veasey","RepVeasey"),
("Filemon Vela","RepFilemonVela"),
("Brian Babin","RepBrianBabin"),
("John Ratcliffe","RepRatcliffe"),
("Kevin Brady","RepKevinBrady"),
("Al Green","RepAlGreen"),
("Rob Bishop","RepRobBishop"),
("Chris Stewart","RepChrisStewart"),
("Robert J. Wittman","RobWittman"),
("Gerald E. Connolly","GerryConnolly"),
("Robert C. \"Bobby\" Scott","BobbyScott"),
("Donald S. Beyer, Jr.","RepDonBeyer"),
("H. Morgan Griffith","RepMGriffith"),
("Peter Welch","PeterWelch"),
("Suzan K. DelBene","RepDelBene"),
("Denny Heck","RepDennyHeck"),
("Rick Larsen","RepRickLarsen"),
("Jaime Herrera Beutler","HerreraBeutler"),
("Dan Newhouse","RepNewhouse"),
("Cathy McMorris Rodgers","cathymcmorris"),
("Derek Kilmer","RepDerekKilmer"),
("Adam Smith","RepAdamSmith"),
("Mark Pocan","repmarkpocan"),
("Ron Kind","RepRonKind"),
("Gwen Moore","RepGwenMoore"),
("Glenn Grothman","RepGrothman"),
("Sean P. Duffy","RepSeanDuffy"),
("David B. McKinley","RepMcKinley"),
("Alexander X. Mooney","RepAlexMooney"),
("Don Young","repdonyoung"),
("Tom O\'Halleran","RepOHalleran"),
("Andy Biggs","RepAndyBiggsAZ"),
("Debbie Lesko","RepDLesko"),
("Ro Khanna","RepRoKhanna"),
("Anna G. Eshoo","RepAnnaEshoo"),
("Zoe Lofgren","RepZoeLofgren"),
("Jimmy Panetta","RepJimmyPanetta"),
("Salud O. Carbajal","RepCarbajal"),
("Adam B. Schiff","RepAdamSchiff"),
("Jimmy Gomez","RepJimmyGomez"),
("Ken Calvert","KenCalvert"),
("Nanette Diaz Barragan","RepBarragan"),
("J. Luis Correa","RepLouCorrea"),
("Duncan Hunter","Rep_Hunter"),
("Rosa L. DeLauro","rosadelauro"),
("Lisa Blunt Rochester","RepLBR"),
("Matt Gaetz","RepMattGaetz"),
("Val Butler Demings","RepValDemings"),
("Charlie Crist","RepCharlieCrist"),
("Brian J. Mast","RepBrianMast"),
("Francis Rooney","RepRooney"),
("Neal P. Dunn","DrNealDunnFL2"),
("Alcee L. Hastings","RepHastingsFL"),
("Theodore E. Deutch","RepTedDeutch"),
("John H. Rutherford","RepRutherfordFL"),
("Al Lawson, Jr.","RepAlLawsonJr"),
("Stephanie N. Murphy","RepStephMurphy"),
("Darren Soto","RepDarrenSoto"),
("A. Drew Ferguson","RepDrewFerguson"),
("John Lewis","repjohnlewis"),
("Bradley Scott Schneider","RepSchneider"),
("Darin LaHood","RepLaHood"),
("Raja Krishnamoorthi","CongressmanRaja"),
("Jim Banks","RepJimBanks"),
("Trey Hollingsworth","RepTrey"),
("Roger W. Marshall","RogerMarshallMD"),
("Ron Estes","RepRonEstes"),
("James Comer","KYComer"),
("Clay Higgins","RepClayHiggins"),
("Mike Johnson","RepMikeJohnson"),
("Anthony G. Brown","RepAnthonyBrown"),
("Steny H. Hoyer","LeaderHoyer"),
("Elijah Cummings","RepCummings"),
("Jamie Raskin","RepRaskin"),
("Chellie Pingree","chelliepingree"),
("Jack Bergman","RepJackBergman"),
("Paul Mitchell","RepPaulMitchell"),
("Ted Budd","RepTedBudd"),
("David Rouzer","RepDavidRouzer"),
("Jeff Fortenberry","JeffFortenberry"),
("Don Bacon","RepDonBacon"),
("Josh Gottheimer","RepJoshG"),
("Adriano Espaillat","RepEspaillat"),
("Eliot L. Engel","RepEliotEngel"),
("Peter T. King","RepPeteKing"),
("Thomas R. Suozzi","RepTomSuozzi"),
("Steve Chabot","RepSteveChabot"),
("Warren Davidson","WarrenDavidson"),
("Peter A. DeFazio","RepPeterDeFazio"),
("Michael Doyle","USRepMikeDoyle"),
("Lloyd Smucker","RepSmucker"),
("Conor Lamb","RepConorLamb"),
("Dwight Evans","RepDwightEvans"),
("Brian Fitzpatrick","RepBrianFitz"),
("Ralph Norman","RepRalphNorman"),
("James E. Clyburn","WhipClyburn"),
("Jim Cooper","repjimcooper"),
("David Kustoff","RepDavidKustoff"),
("Vicente Gonzalez","RepGonzalez"),
("Sheila Jackson Lee","JacksonLeeTX18"),
("Jodey C. Arrington","RepArrington"),
("Michael Cloud","RepCloudTX"),
("Eddie Bernice Johnson","RepEBJ"),
("Lloyd Doggett","RepLloydDoggett"),
("John R. Curtis","RepJohnCurtis"),
("A. Donald McEachin","RepMcEachin"),
("Pramila Jayapal","RepJayapal"),
("Mike Gallagher","RepGallagher"),
("Liz Cheney","RepLizCheney"),
("Doug Jones","SenDougJones"),
("Thomas R. Carper","SenatorCarper"),
("Mike Crapo","MikeCrapo"),
("Richard J. Durbin","SenatorDurbin"),
("Benjamin L. Cardin","SenatorCardin"),
("Richard Burr","SenatorBurr"),
("Sherrod Brown","SenSherrodBrown"),
("James M. Inhofe","JimInhofe"),
("Ron Wyden","RonWyden"),
("Maria Cantwell","SenatorCantwell"),
("Lamar Alexander","SenAlexander"),
("Colin Allred","RepColinAllred"),
("Kelly Armstrong","RepArmstrongND"),
("Cynthia Axne","RepCindyAxne"),
("Sanford D. Bishop","SanfordBishop"),
("Earl Blumenauer","repblumenauer"),
("Roy Blunt","RoyBlunt"),
("Tammy Baldwin","SenatorBaldwin"),
("John Boozman","JohnBoozman"),
("Marsha Blackburn","MarshaBlackburn"),
("Michael F. Bennet","SenatorBennet"),
("Richard Blumenthal","SenBlumenthal"),
("Cory A. Booker","SenBooker"),
("James Baird","RepJimBaird"),
("Anthony Brindisi","RepBrindisi"),
("Tim Burchett","RepTimBurchett"),
("Mike Braun","SenatorBraun"),
("Susan M. Collins","SenatorCollins"),
("Shelley Moore Capito","SenCapito"),
("Ed Case","RepEdCase"),
("John Cornyn","JohnCornyn"),
("Robert P. Casey, Jr.","SenBobCasey"),
("Bill Cassidy","SenBillCassidy"),
("Christopher A. Coons","ChrisCoons"),
("Tom Cotton","SenTomCotton"),
("Kevin Cramer","SenKevinCramer"),
("Ted Cruz","SenTedCruz"),
("Catherine Cortez Masto","SenCortezMasto"),
("Sean Casten","RepCasten"),
("Ben Cline","RepBenCline"),
("Angie Craig","RepAngieCraig"),
("Dan Crenshaw","RepDanCrenshaw"),
("Jason Crow","RepJasonCrow"),
("Joe Cunningham","RepCunningham"),
("Gilbert Ray Cisneros Jr.","RepGilCisneros"),
("TJ Cox","RepTjCox"),
("Steve Daines","SteveDaines"),
("Tammy Duckworth","SenDuckworth"),
("Sharice Davids","RepDavids"),
("Antonio Delgado","repdelgado"),
("Madeleine Dean","RepDean"),
("Joni Ernst","SenJoniErnst"),
("Veronica Escobar","RepEscobar"),
("Dianne Feinstein","SenFeinstein"),
("Deb Fischer","SenatorFischer"),
("Abby Finkenauer","RepFinkenauer"),
("Lizzie Fletcher","RepFletcher"),
("Russ Fulcher","RepRussFulcher"),
("Lindsey Graham","LindseyGrahamSC"),
("Chuck Grassley","ChuckGrassley"),
("Sam Graves","RepSamGraves"),
("Kirsten E. Gillibrand","gillibrandny"),
("Cory Gardner","SenCoryGardner"),
("Sylvia Garcia","RepSylviaGarcia"),
("Anthony Gonzalez","RepAGonzalez"),
("Lance Gooden","RepLanceGooden"),
("Mark Green","RepMarkGreen"),
("Michael Guest","RepMichaelGuest"),
("Jared Golden","RepGolden"),
("Brian Higgins","RepBrianHiggins"),
("Mazie K. Hirono","maziehirono"),
("Martin Heinrich","MartinHeinrich"),
("John Hoeven","SenJohnHoeven"),
("Steven Horsford","RepHorsford"),
("Kamala D. Harris","SenKamalaHarris"),
("Margaret Wood Hassan","SenatorHassan"),
("Cindy Hyde-Smith","SenHydeSmith"),
("Debra Haaland","RepDebHaaland"),
("Jahana Hayes","RepJahanaHayes"),
("Kendra Horn","RepKendraHorn"),
("Chrissy Houlahan","RepHoulahan"),
("Katie Hill","RepKatieHill"),
("Jim Hagedorn","RepHagedorn"),
("Josh Hawley","SenHawleyPress"),
("Johnny Isakson","SenatorIsakson"),
("Ron Johnson","SenRonJohnson"),
("Dusty Johnson","RepDustyJohnson"),
("John Joyce","RepJohnJoyce"),
("Marcy Kaptur","RepMarcyKaptur"),
("Amy Klobuchar","SenAmyKlobuchar"),
("Angus S. King, Jr.","SenAngusKing"),
("Tim Kaine","timkaine"),
("John Kennedy","SenJohnKennedy"),
("Andy Kim","RepAndyKimNJ"),
("Patrick J. Leahy","SenatorLeahy"),
("Nita M. Lowey","NitaLowey"),
("John B. Larson","RepJohnLarson"),
("Stephen F. Lynch","RepStephenLynch"),
("Daniel Lipinski","RepLipinski"),
("James Lankford","SenatorLankford"),
("Mike Lee","SenMikeLee"),
("Susie Lee","RepSusieLee"),
("Elaine Luria","RepElaineLuria"),
("Edward J. Markey","SenMarkey"),
("James P. McGovern","RepMcGovern"),
("Mitch McConnell","SenateMajLdr"),
("Robert Menendez","SenatorMenendez"),
("Jerry Moran","JerryMoran"),
("Patty Murray","PattyMurray"),
("Gregory W. Meeks","RepGregoryMeeks"),
("Lisa Murkowski","lisamurkowski"),
("Christopher Murphy","SenMurphyOffice"),
("Jeff Merkley","SenJeffMerkley"),
("Joe Manchin, III","Sen_JoeManchin"),
("Martha McSally","SenMcSallyAZ"),
("Tom Malinowski","RepMalinowski"),
("Daniel Meuser","RepMeuser"),
("Carol Miller","RepCarolMiller"),
("Debbie Mucarsel-Powell","RepDMP"),
("Lucy McBath","RepLucyMcBath"),
("Ben McAdams","RepBenMcAdams"),
("Richard E. Neal","RepRichardNeal"),
("Joe Neguse","RepJoeNeguse"),
("Alexandria Ocasio-Cortez","AOC"),
("Ilhan Omar","Ilhan"),
("Frank Pallone, Jr.","FrankPallone"),
("Collin C. Peterson","collinpeterson"),
("Rob Portman","senrobportman"),
("Gary C. Peters","SenGaryPeters"),
("Rand Paul","RandPaul"),
("David Perdue","sendavidperdue"),
("Chris Pappas","RepChrisPappas"),
("Greg Pence","RepGregPence"),
("Dean Phillips","RepDeanPhillips"),
("Ayanna Pressley","RepPressley"),
("Katie Porter","RepKatiePorter"),
("Jack Reed","SenJackReed"),
("Pat Roberts","SenPatRoberts"),
("Harold Rogers","RepHalRogers"),
("James E. Risch","SenatorRisch"),
("Marco Rubio","SenRubioPress"),
("Mike Rounds","SenatorRounds"),
("Jacky Rosen","SenJackyRosen"),
("Guy Reschenthaler","GReschenthaler"),
("Denver Riggleman","RepRiggleman"),
("John Rose","RepJohnRose"),
("Max Rose","RepMaxRose"),
("Chip Roy","RepChipRoy"),
("Mitt Romney","SenatorRomney"),
("Harley Rouda","RepHarley"),
("Bernard Sanders","SenSanders"),
("Charles E. Schumer","SenSchumer"),
("F. James Sensenbrenner, Jr.","JimPressOffice"),
("Richard C. Shelby","SenShelby"),
("Brad Sherman","BradSherman"),
("Christopher H. Smith","RepChrisSmith"),
("Debbie Stabenow","SenStabenow"),
("Jeanne Shaheen","SenatorShaheen"),
("Tim Scott","SenatorTimScott"),
("Kyrsten Sinema","SenatorSinema"),
("Brian Schatz","SenBrianSchatz"),
("Ben Sasse","SenSasse"),
("Dan Sullivan","SenDanSullivan"),
("Tina Smith","SenTinaSmith"),
("Donna E. Shalala","RepShalala"),
("Mikie Sherrill","RepSherrill"),
("Elissa Slotkin","RepSlotkin"),
("Abigail Spanberger","RepSpanberger"),
("Greg Stanton","RepGregStanton"),
("Pete Stauber","RepPeteStauber"),
("W. Gregory Steube","RepGregSteube"),
("Haley Stevens","RepHaleyStevens"),
("Kim Schrier","RepKimSchrier"),
("Rick Scott","SenRickScott"),
("Bennie G. Thompson","BennieGThompson"),
("John Thune","SenJohnThune"),
("Patrick J. Toomey","SenToomey"),
("Jon Tester","SenatorTester"),
("Thom Tillis","SenThomTillis"),
("Lori Trahan","RepLoriTrahan"),
("David Trone","RepDavidTrone"),
("Xochitl Torres Small","RepTorresSmall"),
("Tom Udall","SenatorTomUdall"),
("Lauren Underwood","RepUnderwood"),
("Peter J. Visclosky","RepVisclosky"),
("Chris Van Hollen","ChrisVanHollen"),
("Sheldon Whitehouse","SenWhitehouse"),
("Mark R. Warner","MarkWarner"),
("Elizabeth Warren","SenWarren"),
("Michael Waltz","RepMichaelWaltz"),
("Steven Watkins","Rep_Watkins"),
("Ron Wright","RepRonWright"),
("Todd Young","SenToddYoung"),
("Bryan Steil","RepBryanSteil"),
("Josh Harder","RepJoshHarder"),
("Mike Levin","RepMikeLevin"),
("Jesus \"Chuy\" García","RepChuyGarcia"),
("Rashida Tlaib","RepRashida"),
("Jefferson Van Drew","CongressmanJVD"),
("Joseph Morelle","RepJoeMorelle"),
("Troy Balderson","RepBalderson"),
("Kevin Hern","repkevinhern"),
("Mary Gay Scanlon","RepMGS"),
("Susan Wild","RepSusanWild"),
("William Timmons","reptimmons"),
("Van Taylor","RepVanTaylor"),
("Jennifer Wexton","RepWexton"),
("Eleanor Holmes Norton","EleanorNorton"),
("John Barrasso","SenJohnBarrasso"),
("Fred Keller","RepFredKeller"),
("Ross Spano","RepRossSpano"),
("Michael Enzi","SenatorEnzi"),
("Roger Wicker","SenatorWicker"),
("Greg Gianforte","GregForMontana"),
("Andy Levin","RepAndyLevin")
]
